import type { Metadata } from "next";
import "./globals.css";
//import SignIn from '@/app/components/SignIn'
// import Home from "@/app/components/Home";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        {/* <SignIn /> */}
        {children}
      </body>
    </html>
  );
}
